exports.mustDeps = [
    {block: 'reset'},
    {block: 'heading'},
    {block: 'header'},
    {block: 'footer'},
    {block: 'pay'},
    {block: 'promo-code'},
    {block: 'sidebar'},
    {block: 'cart'},
    {block: 'cart-heading'},
    {block: 'section'},
    {block: 'section-heading'},
    {block: 'section-content'},
    {block: 'flex-row'},
    {block: 'flights-wrapper'},
    {block: 'flight'},
    {block: 'flight-notifications'},
    {block: 'travel-extras'},
    {block: 'expandable'},
    {block: 'nav'},
    {block: 'get-extra'},
    {block: 'booking-steps'},
    {block: 'add-extras'},
    {block: 'help-section'},
    {block: 'links-list'},
    {block: 'contacts'}
];
