exports.mustDeps = [
    {block: 'reset'},
    {block: 'heading'},
    {block: 'header'},
    {block: 'footer'},
    {block: 'pay'},
    {block: 'promo-code'},
    {block: 'sidebar'},
    {block: 'cart'},
    {block: 'cart-heading'},
    {block: 'cart-title'},
    {block: 'section'},
    {block: 'section-heading'},
    {block: 'section-content'},
    {block: 'flex-row'},
    {block: 'flights-wrapper'},
    {block: 'flight'},
    {block: 'flight-notifications'},
    {block: 'travel-extras'}
];
